module.exports = {
  plugins: ['@trivago/prettier-plugin-sort-imports'],
  tailwindFunctions: ['cn'],
  importOrder: [
    '^react(.*)$',
    '^[A-Za-z](.*)$',
    '^@/assets(.*)$',
    '^@/layouts(.*)$',
    '^@/pages(.*)$',
    '^@/components(.*)$',
    '^@/store(.*)$',
    '^@/lib(.*)$',
    '^@/constants(.*)$',
    '^@/scss(.*)$',
    '^[./]*interfaces(.*)$',
    '^[./]*services(.*)$',
    '^[./]*stores(.*)$',
    '^[./]*components(.*)$',
    '^[./]*helpers(.*)$',
    '^[./]*constants(.*)$',
    '^[./]',
  ],
  importOrderSeparation: true,
  importOrderSortSpecifiers: true,
  singleQuote: true,
};
